# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x04node\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0cPingResponse\x12\r\n\x05reply\x18\x01 \x01(\t\"\x0f\n\rStatusRequest\"F\n\x0eStatusResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_votes\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t2x\n\x0bNodeService\x12-\n\x04Ping\x12\x11.node.PingRequest\x1a\x12.node.PingResponse\x12:\n\rGetNodeStatus\x12\x13.node.StatusRequest\x1a\x14.node.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=20
  _globals['_PINGREQUEST']._serialized_end=50
  _globals['_PINGRESPONSE']._serialized_start=52
  _globals['_PINGRESPONSE']._serialized_end=81
  _globals['_STATUSREQUEST']._serialized_start=83
  _globals['_STATUSREQUEST']._serialized_end=98
  _globals['_STATUSRESPONSE']._serialized_start=100
  _globals['_STATUSRESPONSE']._serialized_end=170
  _globals['_NODESERVICE']._serialized_start=172
  _globals['_NODESERVICE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
