# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import voting_pb2 as voting__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VotingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitVote = channel.unary_unary(
                '/voting.VotingService/SubmitVote',
                request_serializer=voting__pb2.VoteRequest.SerializeToString,
                response_deserializer=voting__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.QueryResults = channel.unary_unary(
                '/voting.VotingService/QueryResults',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=voting__pb2.VoteResults.FromString,
                _registered_method=True)
        self.PropagateBlock = channel.unary_unary(
                '/voting.VotingService/PropagateBlock',
                request_serializer=voting__pb2.BlockMessage.SerializeToString,
                response_deserializer=voting__pb2.VoteResponse.FromString,
                _registered_method=True)


class VotingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitVote(self, request, context):
        """Voto normal, criptografado e gravado localmente + broadcast
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryResults(self, request, context):
        """Consulta resultados (descriptografa a própria cadeia)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateBlock(self, request, context):
        """RPC interno: recebe blocos de outros nós
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VotingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitVote': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitVote,
                    request_deserializer=voting__pb2.VoteRequest.FromString,
                    response_serializer=voting__pb2.VoteResponse.SerializeToString,
            ),
            'QueryResults': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryResults,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=voting__pb2.VoteResults.SerializeToString,
            ),
            'PropagateBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateBlock,
                    request_deserializer=voting__pb2.BlockMessage.FromString,
                    response_serializer=voting__pb2.VoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voting.VotingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voting.VotingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VotingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voting.VotingService/SubmitVote',
            voting__pb2.VoteRequest.SerializeToString,
            voting__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voting.VotingService/QueryResults',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            voting__pb2.VoteResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voting.VotingService/PropagateBlock',
            voting__pb2.BlockMessage.SerializeToString,
            voting__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
